export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function LandingPageLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <main className="h-full overflow-auto bg-[#cccccc]">
        <div className="w-full h-full max-w-screen-xl mx-auto">
          {children}
        </div>      
      </main> 
  )
}
